### ISSUE TITLE
اندپوینت مورد نظر برای شاتل

### ISSUE THREAD

**Issue by Hesaf-V** [ircfspace/endpoint#2]
سلام خسته نباشید، آبلیوین و کلا فرایند وارپ برای بنده با اینترنت ثابت شاتل کلا کار نمیده
اندپوینت های متعددی هم استفاده میکنم ولی حتی اندپوینت های موردنظر هم کار نمیده (برای اینترنت های دیگه موردی نداره)

**Comment by ircfspace** [comment]
سلام
اگر با اندپوینت‌های پیشنهادی یا اسکنرهای جانبی نتیجه نگرفتین، باید منتظر بروزرسانی بعدی Warp-plus باشین
